Create alto-4-4.xsd
altoxml/schema pull request #77
Opened 2022-04-15 09:01 UTC by cipriandinu

2022-07-07 13:52 UTC, stweil requested changes
It would be nice if some typos which were found by codespell could be fixed.

2022-07-07 13:52 UTC, stweil commented on v4/alto-4-4.xsd
> +					The sequence position of the Gylph element matches the position of the character in the String.
```suggestion
					The sequence position of the Glyph element matches the position of the character in the String.
```

2022-07-07 13:52 UTC, stweil commented on v4/alto-4-4.xsd
> +				<xsd:documentation>Indicates the alignement of the paragraph. Could be left, right, center or justify.</xsd:documentation>
```suggestion
				<xsd:documentation>Indicates the alignment of the paragraph. Could be left, right, center or justify.</xsd:documentation>
```

2022-07-07 13:52 UTC, stweil commented on v4/alto-4-4.xsd
> +	7. Add "ALTERNATIVE" als childs to "STRING" element
```suggestion
	7. Add "ALTERNATIVE" as children to "STRING" element 
```

2022-07-07 13:52 UTC, stweil commented on v4/alto-4-4.xsd
> +				on which the layout is described. Incase the original image is not known
```suggestion
				on which the layout is described. In case the original image is not known
```

2022-07-10 17:42 UTC, cipriandinu commented
Hi Stefan,
Thank you for your comments, we will fix all these typos into next version

2022-09-13 22:19 UTC, cneud commented on v4/alto-4-4.xsd
> +	      			<xsd:documentation>Other languages that appear on this page. Provides a convinient way to summarize all the languages found on a particular page, without parsing the entire file</xsd:docume
This one seems to have been missed by codespell ;)

```suggestion
	      			<xsd:documentation>Other languages that appear on this page. Provides a convenient way to summarize all the languages found on a particular page, without parsing the entire file</xsd:documentation>
```

2023-03-03 08:17 UTC, merged